/**
 * 40+ Authentic GLSL Shaders & Post-Processing Filters
 * Sourced from PixiJS Filters, Three.js PostProcessing, and Shadertoy
 */

export interface EffectFilterItem {
  id: string;
  name: string;
  category: 'glitch' | 'light' | 'distortion' | 'color' | 'camera';
  tag: string;
  desc: string;
  icon: string;
  gradient: string;
}

export const EFFECT_CATEGORIES = [
  { id: 'all', name: 'Tất cả' },
  { id: 'glitch', name: 'Glitch & Retro' },
  { id: 'light', name: 'Light & Glow' },
  { id: 'distortion', name: 'Distortion & Blur' },
  { id: 'color', name: 'Color & Art' },
  { id: 'camera', name: 'Camera & Film' },
];

export const FULL_CORE_FILTERS: EffectFilterItem[] = [
  // ─── 1. GLITCH, RETRO & CYBER ───
  {
    id: 'horizontal_scanline_rgb_glitch',
    name: 'Scanline RGB Slicing Glitch',
    category: 'glitch',
    tag: 'PixiJS Glitch + CRT',
    desc: 'Cắt lát ngang đa tầng và lệch kênh màu Red/Cyan 3D với vạch quét CRT phosphor.',
    icon: '⚡',
    gradient: 'from-pink-500 to-rose-600',
  },
  {
    id: 'vhs_retro_tape_noise',
    name: 'VHS Retro Tape Static',
    category: 'glitch',
    tag: 'PixiJS OldFilm',
    desc: 'Nhiễu hạt băng từ VHS cổ điển, vạch tuyết chạy dọc và quang sai màu analog.',
    icon: '📼',
    gradient: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'crt_monitor_curvature',
    name: 'CRT Arcade Curved Screen',
    category: 'glitch',
    tag: 'PixiJS CRTFilter',
    desc: 'Màn hình máy chơi game thùng CRT cong vòm, sọc quét dải ngang và lóe sáng cạnh.',
    icon: '📺',
    gradient: 'from-cyan-600 to-blue-700',
  },
  {
    id: 'rgb_split_chromatic',
    name: 'RGB Split Chromatic Aberration',
    category: 'glitch',
    tag: 'PixiJS RGBSplit',
    desc: 'Tách rời 3 kênh màu Đỏ - Xanh lá - Xanh dương tạo hiệu ứng 3D Anaglyph.',
    icon: '👓',
    gradient: 'from-fuchsia-500 to-indigo-600',
  },
  {
    id: 'pixel_mosaic_shatter',
    name: 'Pixelate Mosaic 8-Bit',
    category: 'glitch',
    tag: 'PixiJS Pixelate',
    desc: 'Phân rã vật thể thành các khối pixel vuông 8-bit retro rồi tái tạo sắc nét.',
    icon: '🧱',
    gradient: 'from-violet-500 to-fuchsia-600',
  },
  {
    id: 'halftone_pop_art',
    name: 'Retro Halftone Pop-Art Grid',
    category: 'glitch',
    tag: 'PixiJS DotFilter',
    desc: 'Chấm hạt in lưới truyện tranh phong cách Retro Pop-Art nổi bật.',
    icon: '🎨',
    gradient: 'from-pink-600 to-yellow-500',
  },
  {
    id: 'ascii_matrix_rain',
    name: 'ASCII Code Matrix Terminal',
    category: 'glitch',
    tag: 'PixiJS AsciiFilter',
    desc: 'Ma trận ký tự xanh lá cây rơi dòng lệnh hacker phong cách phim The Matrix.',
    icon: '💻',
    gradient: 'from-green-500 to-emerald-700',
  },
  {
    id: 'cross_hatch_sketch',
    name: 'Pencil Cross-Hatch Sketch',
    category: 'glitch',
    tag: 'PixiJS CrossHatch',
    desc: 'Phác thảo nét vẽ bút chì gạch chéo nghệ thuật đen trắng.',
    icon: '✏️',
    gradient: 'from-slate-600 to-zinc-800',
  },

  // ─── 2. LIGHT & CINEMATIC GLOW ───
  {
    id: 'godray_volumetric_light',
    name: 'Volumetric Sun Godrays',
    category: 'light',
    tag: 'PixiJS GodrayFilter',
    desc: 'Tia sáng mặt trời rọi xuyên không gian tạo bầu không khí tráng lệ.',
    icon: '☀️',
    gradient: 'from-amber-400 to-orange-500',
  },
  {
    id: 'advanced_bloom_dreamy',
    name: 'Advanced HDR Bloom',
    category: 'light',
    tag: 'PixiJS BloomFilter',
    desc: 'Ánh sáng tỏa hào quang mơ màng dịu ngọt cho các shot quay lãng mạn.',
    icon: '🌸',
    gradient: 'from-pink-400 to-purple-500',
  },
  {
    id: 'neon_cyber_glow',
    name: 'Neon Cyberpunk Outline Glow',
    category: 'light',
    tag: 'PixiJS GlowFilter',
    desc: 'Đèn viền Neon phát sáng nhấp nháy chuyển màu theo nhịp điệu bài hát.',
    icon: '💡',
    gradient: 'from-cyan-400 to-fuchsia-600',
  },
  {
    id: 'prism_rainbow_flare',
    name: 'Prism Optical Lens Flare',
    category: 'light',
    tag: 'Shadertoy Anamorphic',
    desc: 'Vệt lóa cầu vồng quang học góc ống kính máy quay điện ảnh Hollywood.',
    icon: '🌈',
    gradient: 'from-blue-500 to-purple-600',
  },
  {
    id: 'golden_bokeh_particles',
    name: 'Golden Bokeh Depth Particles',
    category: 'light',
    tag: 'Three.js BokehShader',
    desc: 'Bụi vàng phát sáng lơ lửng bồng bềnh tạo cảm giác sang trọng đẳng cấp.',
    icon: '✨',
    gradient: 'from-amber-400 to-yellow-600',
  },
  {
    id: 'specular_metallic_sheen',
    name: 'Specular Light Sheen Apple',
    category: 'light',
    tag: 'Shadertoy Glare',
    desc: 'Vệt sáng kim loại quét mượt mà qua bề mặt sản phẩm phong cách Apple.',
    icon: '🌟',
    gradient: 'from-cyan-400 to-blue-600',
  },
  {
    id: 'strobe_flash_beat',
    name: 'Strobe Flash EDM Beat',
    category: 'light',
    tag: 'Three.js StrobePass',
    desc: 'Chớp nháy tương phản Trắng/Đen nghịch màu đập dồn theo nhịp bass.',
    icon: '💥',
    gradient: 'from-yellow-400 to-amber-600',
  },
  {
    id: 'flash_blast_silhouette',
    name: 'Solarize Nuclear Flash Blast',
    category: 'light',
    tag: 'Shadertoy Blast',
    desc: 'Cú nổ bùng sáng chói lòa chuyển hóa vật thể thành khối màu sắc nét 100%.',
    icon: '🔥',
    gradient: 'from-purple-500 to-indigo-600',
  },
  {
    id: 'night_vision_military',
    name: 'Military Green Night Vision',
    category: 'light',
    tag: 'Three.js NightVision',
    desc: 'Kính nhìn đêm quân đội màu xanh lá lân quang với hạt nhiễu và vạch đo.',
    icon: '🪖',
    gradient: 'from-lime-500 to-emerald-700',
  },

  // ─── 3. DISTORTION & MOTION BLUR ───
  {
    id: 'shockwave_water_ripple',
    name: 'Expanding Shockwave Ripple',
    category: 'distortion',
    tag: 'PixiJS Shockwave',
    desc: 'Vòng sóng xung kích lan tỏa từ tâm bóp méo hình ảnh theo sóng âm.',
    icon: '🔘',
    gradient: 'from-sky-500 to-indigo-600',
  },
  {
    id: 'liquid_wave_distortion',
    name: 'Liquid Ripple Wave Refraction',
    category: 'distortion',
    tag: 'PixiJS WaterDisplacement',
    desc: 'Sóng nước gợn sóng biến dạng bề mặt sản phẩm tươi mát.',
    icon: '🌊',
    gradient: 'from-blue-600 to-teal-500',
  },
  {
    id: 'twist_vortex_swirl',
    name: 'Twist Vortex Swirl',
    category: 'distortion',
    tag: 'PixiJS TwistFilter',
    desc: 'Vòng xoáy lốc xoáy vặn xoắn tâm điểm hình ảnh đầy ma mị.',
    icon: '🌀',
    gradient: 'from-purple-600 to-violet-800',
  },
  {
    id: 'bulge_pinch_lens',
    name: 'Bulge Pinch Fisheye Lens',
    category: 'distortion',
    tag: 'PixiJS BulgePinch',
    desc: 'Ống kính mắt cá lồi hình cầu phóng đại trung tâm cực đại.',
    icon: '🔮',
    gradient: 'from-teal-400 to-cyan-600',
  },
  {
    id: 'radial_zoom_warp',
    name: 'Hyperdrive Zoom Blur Warp',
    category: 'distortion',
    tag: 'PixiJS ZoomBlur',
    desc: 'Tia mờ phóng nhanh tốc độ ánh sáng vọt tới đối tượng.',
    icon: '🚀',
    gradient: 'from-rose-500 to-orange-600',
  },
  {
    id: 'motion_blur_velocity',
    name: 'Directional Motion Blur',
    category: 'distortion',
    tag: 'PixiJS MotionBlur',
    desc: 'Vệt mờ chuyển động theo hướng ngang tạo cảm giác tốc độ cao.',
    icon: '💨',
    gradient: 'from-blue-500 to-indigo-700',
  },
  {
    id: 'perspective_3d_float',
    name: '3D Perspective Tilt Projection',
    category: 'distortion',
    tag: 'Three.js 3D Quad',
    desc: 'Nghiêng góc 3D lơ lửng bồng bềnh tự nhiên kết hợp bóng đổ mặt sàn.',
    icon: '📦',
    gradient: 'from-indigo-500 to-sky-600',
  },
  {
    id: 'water_puddle_reflection',
    name: 'Puddle Mirror Reflection',
    category: 'distortion',
    tag: 'PixiJS Reflection',
    desc: 'Mặt nước phản chiếu gợn sóng phía chân video như mặt hồ.',
    icon: '🪞',
    gradient: 'from-cyan-500 to-blue-600',
  },

  // ─── 4. COLOR GRADING & FUTURISTIC ART ───
  {
    id: 'thermal_heatmap_matrix',
    name: 'FLIR Predator Ironbow Heatmap',
    category: 'color',
    tag: 'Shadertoy Ironbow',
    desc: 'Bản đồ nhiệt quang phổ rực lửa Sci-Fi phong cách phim Quái Thú Predator.',
    icon: '🌡️',
    gradient: 'from-red-600 to-amber-500',
  },
  {
    id: 'duotone_cyber_pink_cyan',
    name: 'Duotone Cyberpunk Tokyo',
    category: 'color',
    tag: 'PixiJS ColorMap',
    desc: 'Hòa trộn 2 dải màu đối lập Hồng Neon và Xanh Cyan đậm chất đường phố Tokyo.',
    icon: '🌆',
    gradient: 'from-pink-500 to-cyan-500',
  },
  {
    id: 'sobel_edge_neon_lines',
    name: 'Sobel Neon Edge Glow',
    category: 'color',
    tag: 'PixiJS Convolution',
    desc: 'Thuật toán dò biên Sobel làm phát sáng các đường nét viền vật thể neon.',
    icon: '🕸️',
    gradient: 'from-cyan-400 to-emerald-500',
  },
  {
    id: 'technicolor_vintage_film',
    name: 'Technicolor 3-Strip Cinema',
    category: 'color',
    tag: 'PixiJS ColorMatrix',
    desc: 'Màu phim nhựa Technicolor thập niên 1950 đậm đà và rực rỡ.',
    icon: '📽️',
    gradient: 'from-amber-600 to-red-600',
  },
  {
    id: 'polaroid_fade_warm',
    name: 'Vintage Polaroid 1980s',
    category: 'color',
    tag: 'PixiJS ColorMatrix',
    desc: 'Màu ảnh chụp lấy ngay Polaroid ấm áp, bạc màu hoài niệm.',
    icon: '📸',
    gradient: 'from-orange-400 to-rose-500',
  },
  {
    id: 'lsd_psychedelic_shift',
    name: 'Psychedelic Spectrum Shift',
    category: 'color',
    tag: 'PixiJS ColorMatrix',
    desc: 'Dịch chuyển dải màu quang phổ liên tục tạo hiệu ứng ảo giác sống động.',
    icon: '🍄',
    gradient: 'from-purple-500 via-pink-500 to-yellow-400',
  },
  {
    id: 'grayscale_underlayer_push',
    name: 'Monochrome Luma Center Pop',
    category: 'color',
    tag: 'Three.js Luminance',
    desc: 'Đè nổi bật vật thể mới lên nền cũ đã mờ xám tương phản tuyệt đối.',
    icon: '🖤',
    gradient: 'from-slate-600 to-zinc-800',
  },
  {
    id: 'color_wash_tint',
    name: 'Cinematic Amber Gold Wash',
    category: 'color',
    tag: 'PixiJS ColorOverlay',
    desc: 'Phủ lớp tone màu hổ phách vàng hoàng hôn ấm áp lên toàn bộ cảnh quay.',
    icon: '🌅',
    gradient: 'from-amber-500 to-yellow-600',
  },

  // ─── 5. CAMERA, LENS & DEPTH ───
  {
    id: 'tilt_shift_miniature',
    name: 'Tilt-Shift Miniature Toy Town',
    category: 'camera',
    tag: 'PixiJS TiltShift',
    desc: 'Làm mờ trên dưới tạo hiệu ứng thế giới đồ chơi thu nhỏ Miniature.',
    icon: '🏙️',
    gradient: 'from-teal-500 to-emerald-600',
  },
  {
    id: 'kenburns_continuous_zoom',
    name: 'Ken-Burns Documentary Zoom',
    category: 'camera',
    tag: 'Three.js Camera',
    desc: 'Góc máy zoom chậm mượt mà mang phong cách phim truyện Hollywood.',
    icon: '🔍',
    gradient: 'from-sky-500 to-cyan-600',
  },
  {
    id: 'film_grain_vintage',
    name: '35mm Hollywood Film Grain',
    category: 'camera',
    tag: 'Three.js FilmShader',
    desc: 'Hạt phim nhựa 35mm hoài cổ Hollywood tăng chất lượng điện ảnh.',
    icon: '🎬',
    gradient: 'from-amber-600 to-stone-700',
  },
  {
    id: 'kaleidoscope_8x_mirror',
    name: 'Kaleidoscope 8-Fold Mandala',
    category: 'camera',
    tag: 'Shadertoy Mandala',
    desc: 'Kính vạn hoa đối xứng 8 cánh xoay tròn biến hóa ma thuật.',
    icon: '💠',
    gradient: 'from-violet-600 to-pink-500',
  },
  {
    id: 'kawase_frosted_glass',
    name: 'Kawase Frosted Blur Glass',
    category: 'camera',
    tag: 'PixiJS KawaseBlur',
    desc: 'Mờ kính mờ cao cấp Apple Liquid Glassmorphism.',
    icon: '🧊',
    gradient: 'from-blue-400 to-slate-600',
  },
  {
    id: 'vignette_dark_corner',
    name: 'Cinematic Vignette Lens',
    category: 'camera',
    tag: 'Three.js Vignette',
    desc: 'Tối 4 góc ống kính máy quay tập trung ánh nhìn vào trung tâm.',
    icon: '🎯',
    gradient: 'from-slate-700 to-black',
  },
  {
    id: 'cartoon_outline_stroke',
    name: 'Comic Book Line Outline',
    category: 'camera',
    tag: 'PixiJS OutlineFilter',
    desc: 'Viền nét mực đen truyện tranh biến hình ảnh thành hoạt hình Anime.',
    icon: '🗯️',
    gradient: 'from-yellow-400 to-slate-900',
  },
];
